plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jemoji
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-avatar
  - jekyll-sitemap
  - jekyll-seo-tag
titles_from_headings:
  strip_title: true
permalink: /:categories/:year/:month/:day/:slug.html
disqus:
  shortname: 0jesushg
